New functionality: Add selection to XML.
pleonex/Binedi pull request #1
Opened 2018-11-11 14:02 UTC by Artuvazro

A new button has been added which allows to convert the selected data in the hex window to XML nodes.

2018-11-11 23:36 UTC, Artuvazro commented on Binedi/Parser.cs
> +            string[] text_array = text.Split('\0');
Should be
`string[] text_array = Regex.Split(text, "(\0+)");`

2019-02-02 17:10 UTC, pleonex requested changes

2019-02-02 17:10 UTC, pleonex commented on Binedi/Binedi.csproj
> +    <Compile Include="smtDsDict.cs" />
This file is not in the PR, I guess it shouldn't be included in the project file, right?

2019-02-02 17:25 UTC, pleonex approved these changes

2019-02-02 17:25 UTC, merged